### ISSUE TITLE
Lag caused when opening dropdown menus and combos

### ISSUE THREAD

**Issue by Noep2404** [isouravgope/Gruvbox-Kvantum#4]
As the title says, using this theme causes a lot of lag when opening menus in qt apps. 
In dolphin for instance, opening the menu takes multiple seconds, during which the app doesn't respond.

**Comment by isouravgope** [comment]
Not yet adopted for qt6, use only in kvantum in qt5, I use WSL, hence I don't think I will be porting this for newer kvantum(qt6).
You can do this yourself if you like.

**Comment by isouravgope** [comment]
@Noep2404 I will archive this project repo as it is only compatible with qt5. Glad to see a gruvbox lover though.

**Comment by isouravgope** [comment]
Closed as it is only compatible till qt5. For qt6 please port the project if you still want to use this theme.

**Comment by TheSerphh** [comment]
works fine now

**Comment by TheSerphh** [comment]
closing this as i have tested this theme on kde and i3wm. Now the kvantum and qt6ct package seems to be well stable and will not cause any lag.
